Screenshots moved and clear method error solved
Screenshots moved to `screenshots` folder;
Solved exception:
```
   File "G:\Meu Drive\PyBAV\SPyB\libs\uix\addons\kivyplots\mdcharttitle.py", line 42, in clear_titles
     self.remove_widget(self._showing_titles.pop(idx))
 IndexError: pop index out of range
```
and:
```
 kivy.uix.widget.WidgetException: Cannot add <kivymd.uix.label.label.MDIcon object at 0x000002CEE6FAC3C0>, it already has a parent <kivymd.uix.boxlayout.MDBoxLayout object at 0x000002CEE6F929E0>
```